name: main
on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: ['**']

jobs:
  lint-and-test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14.16.0']
    steps:
      - name: Cancel outdated workflows
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Restore node_modules from cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - run: yarn install --frozen-lockfile
      - run: yarn run typecheck
      - run: yarn run build
      - run: npm pack
